version: '3'
services:
  budget_app:
    image: node:8-alpine
    working_dir: /app
    container_name: budget_app
    command: sh -c "yarn && yarn start"
    volumes:
      - ./budget_app:/app
    network_mode: "host"
  budget_api:
    image: node:8-alpine
    working_dir: /app
    container_name: budget_api
    command: sh -c "yarn && yarn start"
    volumes:
      - ./budget_api:/app
    network_mode: "host"